import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import {fixture,event,enqueue,goodAudit,report,deliveredHook} from './helpers.mjs';
import {Engine} from '../plugins/autoreview/src/engine.mjs';
import {capture,changes,materialize} from '../plugins/autoreview/src/snapshot.mjs';
import {git,safeRelative} from '../plugins/autoreview/src/util.mjs';
import {buildAuditInput,languageOf,reviewerInstructions} from '../plugins/autoreview/src/prompts.mjs';

test('unchanged, disabled, and missing-baseline hooks never start a review',t=>{const f=fixture(t);assert.equal(f.engine.hook(event(f.root,'Stop')).skipped,'missing_prompt_baseline');deliveredHook(f.engine,event(f.root,'UserPromptSubmit','t',{prompt:'解释代码'}));assert.equal(f.engine.hook(event(f.root,'Stop','t')).skipped,'no_changes');assert.equal(f.engine.hook(event(f.root,'Stop','t')).skipped,'duplicate_stop');f.engine.configure(f.project.id,{enabled:false});assert.equal(deliveredHook(f.engine,event(f.root,'UserPromptSubmit','x',{prompt:'改代码'})).skipped,'project_not_enabled');});
test('review is silent and never changes source or Git index',async t=>{const f=fixture(t);const {runId}=enqueue(f),before=capture(f.root,f.store),index=git(f.root,['write-tree']);await f.engine.drain();const run=f.engine.run(runId);assert.equal(run.status,'completed');assert.equal(run.language,'zh');assert.equal(capture(f.root,f.store).digest,before.digest);assert.equal(git(f.root,['write-tree']),index);assert.ok(f.store.events(runId).every(e=>e.type==='status'));assert.equal(typeof f.engine.apply,'undefined');assert.equal(typeof f.engine.undo,'undefined');});
test('next prompt receives validated advice once, without changing its original requirements',async t=>{const f=fixture(t);const {runId}=enqueue(f);await f.engine.drain();const prompt='接下来增加错误处理';const r=deliveredHook(f.engine,event(f.root,'UserPromptSubmit','two',{prompt}));assert.match(r.additionalContext,/待传达审计队列/);assert.match(r.additionalContext,/main.js/);assert.match(r.additionalContext,/本轮用户要求为准/);assert.equal(f.engine.run(runId).deliveredTurnId,'two');assert.equal(deliveredHook(f.engine,event(f.root,'UserPromptSubmit','two',{prompt:'补充约束'})).additionalContext,undefined);f.engine.hook(event(f.root,'Stop','two'));assert.equal(deliveredHook(f.engine,event(f.root,'UserPromptSubmit','three',{prompt:'继续'})).additionalContext,undefined);assert.ok(Object.values(f.store.state.turns).some(t=>t.prompts.includes(prompt)));});
test('advice does not cross sessions and is not consumed by another session',async t=>{const f=fixture(t);enqueue(f);await f.engine.drain();assert.equal(f.engine.hook({...event(f.root,'UserPromptSubmit','other',{prompt:'其他需求'}),session_id:'other'}).additionalContext,undefined);assert.ok(deliveredHook(f.engine,event(f.root,'UserPromptSubmit','next',{prompt:'继续'})).additionalContext);});
test('changed source still delivers the frozen report with an explicit recheck marker',async t=>{const f=fixture(t);const {runId}=enqueue(f);await f.engine.drain();f.write('related.js','changed');const r=deliveredHook(f.engine,event(f.root,'UserPromptSubmit','next',{prompt:'继续'}));assert.match(r.additionalContext,/\"sourceChanged\":true/);assert.match(r.additionalContext,/重新核对/);assert.ok(f.engine.run(runId).sourceChangedAtDelivery);});
test('new input does not block or cancel a running immutable review',async t=>{let begin,finish;const started=new Promise(r=>begin=r);let signal;const f=fixture(t,{audit:o=>{signal=o.signal;begin();return new Promise(r=>finish=r);}});const {runId}=enqueue(f),working=f.engine.drain();await started;const result=deliveredHook(f.engine,event(f.root,'UserPromptSubmit','two',{prompt:'新的需求'}));assert.equal(result.additionalContext,undefined);assert.equal(signal.aborted,false);f.write('main.js','user is editing');finish(structuredClone(report));await working;assert.equal(f.engine.run(runId).status,'completed');assert.equal(fs.readFileSync(path.join(f.root,'main.js'),'utf8'),'user is editing');});
test('queued snapshots are replaced by the newest turn',t=>{const f=fixture(t);const {runId}=enqueue(f);deliveredHook(f.engine,event(f.root,'UserPromptSubmit','two',{prompt:'第二轮'}));f.write('main.js','new code');f.engine.hook(event(f.root,'Stop','two'));assert.equal(f.engine.run(runId).status,'cancelled');assert.equal(f.store.state.runs.filter(r=>r.status==='queued').length,1);});
test('pause cancels running review and suppresses result',async t=>{let begin;const started=new Promise(r=>begin=r);const f=fixture(t,{audit:({signal})=>new Promise((resolve,reject)=>{begin();signal.addEventListener('abort',()=>reject(new Error('abort')),{once:true});})});const {runId}=enqueue(f),work=f.engine.drain();await started;f.engine.configure(f.project.id,{enabled:false});await work;assert.equal(f.engine.run(runId).status,'cancelled');assert.deepEqual(f.engine.run(runId).findings,[]);});
test('failed or invalid reports are never delivered',async t=>{for(const mutate of [r=>{throw new Error('model unavailable');},r=>{r.findings[0].confidence='low';return r;},r=>{r.findings[0].line=999;return r;},r=>{r.findings[0].suggestion='Use three';return r;},r=>{r.findings[0].file='../escape';return r;}]){const f=fixture(t,{audit:async()=>mutate(structuredClone(report))});const {runId}=enqueue(f);await f.engine.drain();assert.equal(f.engine.run(runId).status,'failed');assert.equal(deliveredHook(f.engine,event(f.root,'UserPromptSubmit','next',{prompt:'继续'})).additionalContext,undefined);}});
test('unexpected snapshot mutation rejects report without touching source',async t=>{const f=fixture(t,{audit:async({cwd})=>{fs.writeFileSync(path.join(cwd,'main.js'),'forbidden write');return structuredClone(report);}});const {runId}=enqueue(f);await f.engine.drain();assert.equal(f.engine.run(runId).status,'failed');assert.equal(fs.readFileSync(path.join(f.root,'main.js'),'utf8'),'export const value = 2;\n');});
test('prompt input is bounded JSON with latest requirements, isolated evidence, and language',t=>{const f=fixture(t);const {runId}=enqueue(f),run=f.engine.run(runId);run.requirements=Array.from({length:15},(_,i)=>`历史${i}`+'x'.repeat(10000));run.requirements.push(run.prompt);const input=JSON.parse(buildAuditInput(run,f.store));assert.equal(input.outputLanguage,'zh');assert.equal(input.latestRequirement,'将数值改为三。');assert.equal(input.requirements.at(-1),run.prompt);assert.equal(input.historyTruncated,true);assert.match(input.beforeAfterEvidence,/value = 2/);assert.match(reviewerInstructions,/全程静默/);assert.match(reviewerInstructions,/不得修改/);assert.equal(languageOf('Check the empty input'), 'en');});
test('an English request receives an English final summary',async t=>{const f=fixture(t,{audit:async()=>({summary:'clean',findings:[],limitations:[]})});deliveredHook(f.engine,event(f.root,'UserPromptSubmit','one',{prompt:'Check empty inputs'}));f.write('main.js','new source');const {runId}=f.engine.hook(event(f.root,'Stop'));await f.engine.drain();assert.equal(f.engine.run(runId).report,'No bugs with sufficient evidence found.');});
test('manual reports join the current project queue for the next conversation message',async t=>{const f=fixture(t);const run=f.engine.manual(f.project.id,'检查代码');await f.engine.drain();assert.equal(f.engine.run(run.id).status,'completed');assert.match(deliveredHook(f.engine,event(f.root,'UserPromptSubmit','one',{prompt:'继续'})).additionalContext,/manual_snapshot/);});
test('interrupt suppresses late Stop without stopping other immutable reviews',t=>{const f=fixture(t);deliveredHook(f.engine,event(f.root,'UserPromptSubmit','one',{prompt:'改代码'}));f.write('main.js','interrupted');f.engine.hook(event(f.root,'Interrupt'));assert.equal(f.engine.hook(event(f.root,'Stop')).skipped,'duplicate_stop');});
test('restart cancels pending work without replaying model calls',async t=>{const f=fixture(t);const {runId}=enqueue(f);const engine=new Engine({store:f.store});assert.equal(engine.run(runId).status,'cancelled');await engine.close();});
test('captures this turn without treating existing dirty files as new changes',t=>{const f=fixture(t);f.write('earlier.js','earlier');deliveredHook(f.engine,event(f.root,'UserPromptSubmit','one',{prompt:'新增代码'}));f.write('new.js','new');const {runId}=f.engine.hook(event(f.root,'Stop'));assert.deepEqual(f.engine.run(runId).changedPaths,['new.js']);});
test('snapshots preserve additions, deletions, tracked ignored files, and reject unsafe paths',t=>{const f=fixture(t),before=capture(f.root,f.store);f.write('.gitignore','main.js\n');f.write('new file.js','new');const after=capture(f.root,f.store),copy=path.join(f.dir,'copy');materialize(after,copy,f.store);assert.equal(capture(copy,f.store).digest,after.digest);fs.unlinkSync(path.join(f.root,'main.js'));assert.ok(changes(before,capture(f.root,f.store)).includes('main.js'));for(const name of ['../x','/x','.git/config','a\\b'])assert.equal(safeRelative(name),false);});
test('credential paths and symlink targets are excluded',t=>{const f=fixture(t);f.write('.env','secret');f.write('.npmrc','secret');f.write('private.key','secret');if(process.platform!=='win32')fs.symlinkSync('/etc/hosts',path.join(f.root,'link'));const snap=capture(f.root,f.store);for(const name of ['.env','.npmrc','private.key','link'])assert.equal(snap.files[name],undefined);});

test('pausing one project preserves another running review and their completed advice stays isolated',async t=>{
 let begin,finish,calls=0;const ready=new Promise(resolve=>begin=resolve);
 const a=fixture(t,{audit:async()=>{if(++calls===1){begin();return new Promise(resolve=>finish=resolve);}return structuredClone(report);}}),b=fixture(t);
 const projectB=a.engine.enable(b.root),runA=a.engine.manual(a.project.id,'检查项目 A'),runB=a.engine.manual(projectB.id,'检查项目 B');
 const first=a.engine.drain();await ready;a.engine.configure(projectB.id,{enabled:false});assert.equal(a.engine.run(runB.id).status,'cancelled');assert.equal(a.engine.run(runA.id).status,'reviewing');
 a.engine.enable(b.root);const nextB=a.engine.manual(projectB.id,'再次检查项目 B');finish(structuredClone(report));await first;await a.engine.drain();assert.equal(a.engine.run(nextB.id).status,'completed');
 const advice=deliveredHook(a.engine,event(a.root,'UserPromptSubmit','next',{prompt:'继续项目 A'}));assert.deepEqual(JSON.parse(advice.additionalContext.split('\n')[1]).reports.map(r=>r.reviewId),[runA.id]);
 assert.deepEqual(a.engine.state.adviceQueue.map(q=>q.runId),[nextB.id]);
});
